---
  extends: eslint-config-airbnb

  env:
    browser: true
    node: true
    es6: true

  parser: babel-eslint
  parserOptions:
   ecmaVersion: 6
   sourceType: "module"
   ecmaFeatures:
    jsx: true

  globals:
    __DEV__: true
    __SERVER__: true

  plugins:
    - react

  rules:
    valid-jsdoc: 2

    object-shorthand: 0
    no-shadow: 0
    class-methods-use-this: 0
    no-console: 0
    no-unresolved: 0
    import/no-unresolved: 0
    no-else-return: 0
    arrow-body-style: 0
    no-new: 0
    no-param-reassign: 0

    jsx-filename-extension: 0
    jsx-quotes: 0

    import/no-named-as-default: 0
    import/no-named-as-default-member: 0
    import/extensions: 0

    react/no-string-refs: 0
    react/prefer-stateless-function: 0
