files:
  include: 'public/assets/css/*.scss'
  ignore: 'public/assets/css/plugin/*.scss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero:
    - 0
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: true
  clean-import-paths:
    - 0
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 0
    - ignore-single-line-rulesets: true
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 0
    - include: true
  force-attribute-nesting: 1
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  # hex-length:
  #   - 1
  #   - style: long
  # hex-notation:
  #   - 1
  #   - style: lowercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 0
    - include: false
  mixin-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  # @todo
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 0
  # @todo
  # no-misspelled-properties:
  #   - 1
  #   - extra-properties: []
  # @todo
  # no-qualifying-elements:
  #   - 1
  #   - allow-element-with-attribute: false
  #     allow-element-with-class: false
  #     allow-element-with-id: false
  no-trailing-zero: 0
  no-transition-all: 0
  no-url-protocols: 1
  no-vendor-prefixes:
    - 0
    - additional-identifiers: []
      excluded-identifiers: []
  placeholder-in-extend: 1
  placeholder-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  property-sort-order: 0
  quotes:
    - 1
    - style: single
  shorthand-values:
    - 0
    - allowed-shorthands:
        - 1
        - 2
        - 3
  single-line-per-selector: 0
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 0
  variable-for-property:
    - 0
    - properties: []
  variable-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 0
